services:
    web:
        image: nginx
        volumes:
            - ./www:/var/www/
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=gammatec.ci-web.dev

networks:
  default:
    external: true
    name: mynet

